---
# tasks file for cisco-nexus-stig

- name: "SRG-NET-000019-RTR-000007"
  ansible.builtin.include_tasks: SV-221076r999685_rule.yml
  when: stig_rules.SRG_NET_000019_RTR_000007 | bool | default(true)

- name: "SRG-NET-000131-RTR-000083"
  ansible.builtin.include_tasks: SV-221078r999687_rule.yml
  when: stig_rules.SRG_NET_000131_RTR_000083 | bool | default(true)

- name: "SRG-NET-000205-RTR-000015"
  ansible.builtin.include_tasks: SV-221095r999704_rule.yml
  when: stig_rules.SRG_NET_000205_RTR_000015 | bool | default(true)

- name: "SRG-NET-000362-RTR-000111"
  ansible.builtin.include_tasks: SV-221082r999691_rule.yml
  when: stig_rules.SRG_NET_000362_RTR_000111 | bool | default(true)

- name: "SRG-NET-000362-RTR-000113"
  ansible.builtin.include_tasks: SV-221084r999693_rule.yml
  when: stig_rules.SRG_NET_000362_RTR_000113 | bool | default(true)

- name: "SRG-NET-000362-RTR-000115"
  ansible.builtin.include_tasks: SV-221085r999694_rule.yml
  when: stig_rules.SRG_NET_000362_RTR_000115 | bool | default(true)

- name: "SRG-NET-000364-RTR-000111"
  ansible.builtin.include_tasks: SV-221097r999706_rule.yml
  when: stig_rules.SRG_NET_000364_RTR_000111 | bool | default(true)

- name: "SRG-NET-000364-RTR-000111"
  ansible.builtin.include_tasks: SV-221098r999707_rule.yml
  when: stig_rules.SRG_NET_000364_RTR_000112 | bool | default(true)

- name: "SRG-NET-000205-RTR-000015"
  ansible.builtin.include_tasks: SV-221116r999725_rule.yml
  when: stig_rules.SRG_NET_000205_RTR_000015 | bool | default(true)

- name: "SRG-NET-000078-RTR-000001"
  ansible.builtin.include_tasks: SV-221086r999695_rule.yml
  when: stig_rules.SRG_NET_000078_RTR_000001 | bool | default(true)
  
- name: "SRG-NET-000364-RTR-000113"
  ansible.builtin.include_tasks: SV-221099r999708_rule.yml
  when: stig_rules.SRG_NET_000364_RTR_000113 | bool | default(true)

- name: "SRG-NET-000512-RTR-000013"
  ansible.builtin.include_tasks: SV-237757r999761_rule.yml
  when: stig_rules.SRG_NET_000512_RTR_000013 | bool | default(true)

- name: "RG-NET-000364-RTR-000111"
  ansible.builtin.include_tasks: SV-221096r999705_rule.yml
  when: stig_rules.SRG_NET_000364_RTR_000111 | bool | default(true)

- name: "SRG-NET-000362-RTR-000112"
  ansible.builtin.include_tasks: SV-221083r999692_rule.yml
  when: stig_rules.SRG_NET_000362_RTR_000112 | bool | default(true)

- name: "SV_21101r999710_rule"                                       # SRG NET id name needed
  ansible.builtin.include_tasks: SV-221101r999710_rule.yml
  when: stig_rules.SV_21101r999710_rule | bool | default(true)