# DISA SRG:       SRG-NET-000078-RTR-000001
# Severity:       low
# Rule ID:        SV-221086r999695_rule
# Identifiers:    SV-110991, V-101887, CCI-000134

- name: Include utility task to find Layer 3 interfaces
  ansible.builtin.include_tasks: utility/find_layer3.yml

# if allowed_inbound_traffic not updated, makes sure doesn't crash on undefined/ None
- name: If allowed_inbound_traffic is undefined or None set empty list
  set_fact:
    allowed_inbound_traffic_sanitized: "{{ allowed_inbound_traffic | default([]) }}"

# sends warning if no allowed_inbound_traffic was added
- name: Warn if allowed_inbound_traffic is empty
  debug:
    msg: "WARNING: allowed_inbound_traffic under vars/main.yml not defined. ACL will only contain 'deny ip any any log'"
  when: allowed_inbound_traffic_sanitized | length == 0

# builds rule set list
- name: Build full ACL rule set
  set_fact:
    acl_rules: >-
      {{
        allowed_inbound_traffic_sanitized | zip(range(10, 10 + allowed_inbound_traffic_sanitized | length * 10, 10)) |
        map('reverse') |
        map('join', ' ') |
        list + ['90 deny ip any any log']
      }}

# creates list from acl_rules
- name: Create ACL with allow-list
  cisco.nxos.nxos_config:
    lines: "{{ acl_rules }}"
    parents: ip access-list EXTERNAL_ACL

- name: Apply ACL to L3 interfaces
  cisco.nxos.nxos_config:
    lines:
      - ip access-group EXTERNAL_ACL in
    parents: "interface {{ item }}"
  loop: "{{ l3_interfaces }}"
