---
# vars file for cisco-nexus-stig

ntp_servers:
  - 8.8.8.8

#
# The `stig_rules` variable is used to define the specific STIG rules
# that are being implemented in this role. Each key corresponds to a
# specific STIG rule, and the value is set to `true` to indicate that
# the rule is being enforced. This allows for easy reference and
# management of the STIG compliance within the role.
# The rules are identified by their unique identifiers, such as
# SRG_NET_000131_RTR_000083, or SRG_NET_000019_RTR_000007, which
# correspond to specific security requirements for network devices.
#
# By setting these rules to `true`, it indicates that the role is
# configured to comply with these security guidelines.
#
# This structure allows for clear documentation and
# management of compliance requirements within the Ansible role.
#
stig_rules:
  SRG_NET_000019_RTR_000007: false
  SRG_NET_000131_RTR_000083: false
  SRG_NET_000205_RTR_000015: false
  SRG_NET_000362_RTR_000111: false
  SRG_NET_000362_RTR_000113: false
  SRG_NET_000364_RTR_000113: false
  SRG_NET_000362_RTR_000115: false
  SRG_NET_000364_RTR_000111: false
  SRG_NET_000364_RTR_000112: false
  SRG_NET_000512_RTR_000004: false
  SRG_NET_000078_RTR_000001: false
  SRG_NET_000512_RTR_000013: false
  SRG_NET_000362_RTR_000112: false
  SV_21101r999710_rule: true          # SRG NET id name needed

#
# The `external_interfaces` variable is used to specify the interfaces
# that are considered external and should be configured accordingly.
# These interfaces are typically connected to external networks or devices,
# or commonly refered to as "uplink" interfaces.
#
external_interfaces:
  - Ethernet1/30
  - Ethernet1/31
  - Ethernet1/32
  - Ethernet1/14-17

# 
# Globally disable CDP on all interfaces
#
cisco_nxos_disable_cdp: true


allowed_inbound_traffic:
# Format: "- permit|deny <protocol> <source> <destination> [eq <port>] [log]"

allowed_outbound_traffic:
# Format: "- permit|deny <protocol> <source> <destination> [eq <port>] [log]"

allowed_ipv6_ula_ranges:
  - "fc00::/7"
  - "fe80::/10"